import tkinter


pages = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
pageInformation = ["The network analysis tool generates user friendly reports automatically, you can find these reports in the 'reports' folder inside the directory you ran the program from. These reports can be viewed with any text editor",
                    "After the program initially runs, you will be able to input any one of the many processes that it has highlighted into the process file lookup tool. You can do this easily by first highlighting the processes full name (including .exe for example, ie for syshost.exe input syshost.exe) and then right clicking to copy it. You can then immediately right click anywhere inside your terminal and it will be automatically pasted into the correct place",
                    "When you run the process lookup for a specific process it provides you with 1. The Processes name and PID. This PID is a unique process identifier that is assigned to each individual process by your operating system. 2. The root path of the process file. 3. Whether this path is a verified or 'official/safe' path",
                    "In the summary generated about active connections, the information is layed out for each connection as RISK, PROCESS NAME, CONNECTION IP, PROTOCOL, ASN NAME, ORG NAME, ORG LOCATION",
                    "Many processes are actually multiple processes running in conjuction, so when you input a certain process into the process file lookup tool you may be presented with many processes",
                    "The reports that are automatically generated by the tool on startup contain a list of all the active connections currently on your device",]

counter = 0



# This function can be called at the press of some button and will generate a window with help information.

def createPopupHelpWindow():
    try:
        global pages
        global counter
        
        #Tkinter automatically creates a smaller window, the "root" window. Even when I create my custom one, so these next lines are to remove that window.
        rootWindow = tkinter.Tk()
        rootWindow.withdraw()


        popupWindow = tkinter.Toplevel()
        popupWindow.title("Help Tab")
        popupWindow.geometry("500x400")
        popupWindow.resizable(True, True)
        
        #I cannot set the backgorund color of the window directly and must instead use this configure call to set it
        popupWindow.configure(background = "black")

        Page1Info = tkinter.Label(popupWindow, text=f"Help Page {pages[counter]}.", font = (20), height = 10, background = "black", fg = "green")
        PageHelpInfo = tkinter.Label(popupWindow, text=f"{pageInformation[counter]}.", font = (10), wraplength = 400, borderwidth = 2, relief = "solid", highlightbackground = "red", highlightthickness = 2, background = "black", fg = "green")

        #I have to use lambda syntax in order to pass a function with parameters to a button, otherwise its not needed
        Page1Button = tkinter.Button(popupWindow, text="Next Page", width = 12, font = ("bold"), command = lambda: nextPage(popupWindow), background = "black", fg = "green")
        exitButton = tkinter.Button(popupWindow, text="Close Help Tab", width = 12, font = ("bold"), command = popupWindow.destroy, background = "black", fg = "green")

        Page1Info.pack()
        PageHelpInfo.pack(padx = 10)
        Page1Button.pack(side = "left", padx = 50)
        exitButton.pack(side = "right", padx = 50)



        #This line keeps the window open, otherwise it closes after 1 frame.
        popupWindow.wait_window()


    except Exception:

        Page1Info = tkinter.Label(popupWindow, text=f"This is the final help page.", font = (20), height = 10, background = "black", fg = "green")

        #I have to use lambda syntax in order to pass a function with parameters to a button, otherwise its not needed
        
        exitButton = tkinter.Button(popupWindow, text="Close Help Tab", width = 12, font = ("bold"), command = popupWindow.destroy, background = "black", fg = "green")

        Page1Info.pack()
        
        exitButton.pack(side = "bottom", pady = 20)



        #This line keeps the window open, otherwise it closes after 1 frame.
        popupWindow.wait_window()


def nextPage(window):
    global counter
    counter += 1
    window.destroy()
    createPopupHelpWindow()
    

